import { useState } from "react";
import { motion } from "framer-motion";
import { Dna, Shield, Clock, Sparkles } from "lucide-react";

interface EvolutionResult {
  task_id: string;
  plan: string;
  mode: string;
}

function SelfEvolve() {
  const [prompt, setPrompt] = useState("");
  const [dryRun, setDryRun] = useState(true);
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<EvolutionResult | null>(null);
  const [history] = useState([
    { prompt: "Switch to dark theme", mode: "preview", time: "12:30" },
    { prompt: "Install development tools", mode: "applied", time: "11:15" },
  ]);

  const handleEvolve = async () => {
    if (!prompt.trim() || isLoading) return;
    setIsLoading(true);

    try {
      const res = await fetch("/api/v1/evolve", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim(), dry_run: dryRun }),
      });
      const data = await res.json();
      setResult({
        task_id: data.task_id ?? "preview-001",
        plan: data.plan ?? `Analyzing: "${prompt}"\nGenerating modification plan...`,
        mode: dryRun ? "dry_run" : "execute",
      });
    } catch {
      setResult({
        task_id: "preview-local",
        plan: `Plan for: "${prompt}"\n\nThis would be generated by the AI orchestrator when connected.`,
        mode: "dry_run",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <motion.div
      className="page"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.3 }}
    >
      <div className="page-header">
        <Dna size={22} style={{ color: "#EA4335" }} />
        <div>
          <h1>Self-Evolve</h1>
          <span className="subtitle">Restructure your OS with natural language</span>
        </div>
      </div>

      <div className="evolve-input-section">
        <textarea
          className="evolve-input"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder='Describe what you want to change... e.g. "Make the UI more minimal" or "Install Python ML tools"'
        />
        <div className="evolve-controls">
          <label className="evolve-toggle">
            <input
              type="checkbox"
              checked={dryRun}
              onChange={(e) => setDryRun(e.target.checked)}
            />
            Preview only (dry run)
          </label>
          <button
            className="evolve-btn"
            onClick={handleEvolve}
            disabled={!prompt.trim() || isLoading}
          >
            <Sparkles size={16} />
            {dryRun ? "Preview" : "Apply Evolution"}
          </button>
        </div>
      </div>

      {result && (
        <div className="evolve-result">
          <div className="result-header">
            <span className={`result-badge ${result.mode}`}>
              {result.mode === "dry_run" ? "Preview" : "Executed"}
            </span>
            <span className="result-task-id">{result.task_id}</span>
          </div>
          <pre className="result-plan">{result.plan}</pre>
        </div>
      )}

      <div className="evolve-safety">
        <Shield size={20} style={{ color: "#34A853", flexShrink: 0 }} />
        <div>
          <h3>Safety Guarantees</h3>
          <ul>
            <li>Automatic snapshot before any change</li>
            <li>One-click rollback to previous state</li>
            <li>Critical system files are protected</li>
            <li>Maximum 10 snapshots retained</li>
          </ul>
        </div>
      </div>

      <div className="evolve-history">
        <h2><Clock size={16} /> Recent Evolutions</h2>
        <div className="history-list">
          {history.map((item, i) => (
            <motion.div
              key={i}
              className="history-item"
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.08 }}
            >
              <span className={`history-badge ${item.mode}`}>
                {item.mode}
              </span>
              <span className="history-prompt">{item.prompt}</span>
              <span className="history-time">{item.time}</span>
            </motion.div>
          ))}
        </div>
      </div>
    </motion.div>
  );
}

export default SelfEvolve;
