# ============================================================
# Gemini OS — Calamares Installer Configuration
# ============================================================

modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  - id: geminios
    module: shellprocess
    config: shellprocess-geminios.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - services-systemd
      - shellprocess@geminios
      - grubcfg
      - bootloader
      - umount
  - show:
      - finished

branding: geminios

prompt-install: true
dont-chroot: false
